### ISSUE TITLE
Cmd: Error when using alfred3 run -m

### ISSUE THREAD

**Issue by mate-code** [ctreffe/alfred#140] opened 2021-11-12 16:02 UTC
When I render my experiment through the command line using `alfred3 run -m` in order to not open a browser window, I get an error:

![image](https://user-images.githubusercontent.com/33900106/141496538-7e938fd1-f966-459e-a082-d37bd51332fd.png)

**Comment by jobrachem** [comment] 2021-11-12 18:00
I cannot reproduce the bug on my machine. Am I right in assuming that you are running alfred3 on windows? Does the alternative way of using 

```
if __name__ == "__main__":
    exp.run(open_browser=False)
```

and executing the script.py directly work for you?

**Comment by mate-code** [comment] 2021-11-16 09:47
I am running alfred3 on Windows and also tried passing the configuration directly like in your example, but it still didn't work.

**Comment by jobrachem** [comment] 2022-05-05 16:09
@ctreffe can you reproduce the issue?

**Comment by ctreffe** [comment] 2022-05-05 16:12
No, the command works fine with my current version of alfred3 (2.3.2b8) on Windows 10

**Comment by jobrachem** [comment] 2022-05-05 16:14
I'll close this for now. If it resurfaces, we can reopen the issue

**Closed by jobrachem** 2022-05-05 16:14 UTC
