### ISSUE TITLE
Cannot abort experiments on first page using on_first_show() or on_every_show()

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#267] opened 2024-04-28 20:49 UTC
Based on the [alfred3 documentation](https://alfredo3.psych.bio.uni-goettingen.de/docs/generated/alfred3.experiment.ExperimentSession.abort.html?highlight=abort#alfred3.experiment.ExperimentSession.abort), I expect to be able to abort an experiment from every page and every page hook. However, the following code works as expected in a single page experiment when using the _on_exp_access_ hook, but not when using _on_first_show_ or _on_every_show_:

```
import alfred3 as al
from datetime import datetime
exp = al.Experiment()

@exp.member
class SinglePage(al.Page):
    title = "Hello World"
    name = "my_page"

    def on_exp_access(self):
        current_time = datetime.now()

        if not current_time.isoweekday() < 6:
            self.exp.abort(
                reason="inactive",
                title="Experiment inactive",
                icon="users",
                msg="The experiment is inactive on weekends."
            )
```

Changing _on_exp_access_ to either _on_first_show_ or _on_every_show_ yields the following error:

```
2024-04-28 22:45:59,946 - exp.default_id - ERROR - experiment id=default_id - session id=sid-8e2fc5b22172454eac5c73aa1e5408fa - Exception during experiment startup.
Traceback (most recent call last):
  File "/Users/ctreffe/.venv/alfred3/lib/python3.12/site-packages/alfred3/localserver.py", line 77, in start
    script.exp_session._start()
  File "/Users/ctreffe/.venv/alfred3/lib/python3.12/site-packages/alfred3/experiment.py", line 939, in _start
    self.user_interface_controller.start()
  File "/Users/ctreffe/.venv/alfred3/lib/python3.12/site-packages/alfred3/ui_controller.py", line 913, in start
    self.exp.movement_manager.start()
  File "/Users/ctreffe/.venv/alfred3/lib/python3.12/site-packages/alfred3/ui_controller.py", line 523, in start
    self.current_page._on_showing_widget(show_time=time.time())
  File "/Users/ctreffe/.venv/alfred3/lib/python3.12/site-packages/alfred3/page.py", line 253, in _on_showing_widget
    raise AbortMove
alfred3.exceptions.AbortMove
```

I think this might be a bug or maybe we need to outline relevant limitations on the usage of the abort() method?

**Comment by jobrachem** [comment] 2024-04-28 20:51
So that means, instead of aborting in a controlled way, the experiment crashes?

**Comment by ctreffe** [comment] 2024-04-28 21:05
Exactly. Sorry, I cropped to much of the console output, the experiment returns a 500 server error when this happens.

**Comment by jobrachem** [comment] 2024-04-28 21:07
Sounds like a bug to me. The `AbortMove` exception should be handled, and the experiment should be aborted in a controlled way. I'll look into it 👍

**Comment by jobrachem** [comment] 2024-04-29 13:07
Ok, I found out what went wrong. The issue occurs *only* if you abort in an `on_first_show` or `on_each_show` hook on *the first page*, because the `AbortMove` exception was not handled during experiment startup. The issue is fixed in https://github.com/ctreffe/alfred/pull/268

**Closed** 2024-05-10 20:31 UTC
Labels: bug
