### ISSUE TITLE
Improve test mode documentation

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#250] opened 2024-02-12 15:55 UTC
Improve Test Mode documentation: Hint about possibility to start experiments in test mode via exp.run() with an argument, which is very important when developing experiments locally (easier to turn on/off than editing the config.conf)

**Comment by jobrachem** [comment] 2024-02-12 16:03
This is a duplicate of #190

**Closed by jobrachem** 2024-02-12 16:03 UTC
Labels: documentation
